const services = [
  {
    name: "Mercedes-Benz M-Class",
    price: "$95,000",
    desc1:
      "Mercedes-Benz M-Class is a SUVIt is available in 4 variants, 1 engine option. Other key specifications of the M-Class include a Kerb Weight of 2175 kg and Bootspace of 690 litres. The M-Class is available in 3 colours. The mileage of M-Class is 15.26 kmpl.",
    desc2:
      "The Mercedes-Benz GLE-Class, formerly Mercedes-Benz M-Class, is a mid-size luxury SUV produced by the German automaker Mercedes-Benz since 1997. In terms of size, it is slotted in between the smaller GLC-Class (based on the C-Class) and the larger GLS-Class, the latter with which it shares platforms.Mercedes joins our list of luxury cars with the best resale value thanks to the CLS-Class, a large luxury sedan. Good reliability scores and strong performance help this Benz hold its value.",
    desc3:
      "All versions get permanent four-wheel drive, while 350 CDI models are fitted with an off-road button that tunes the traction control for slippery conditions.The average rating is a 3.6 out of 5 stars. The Mercedes-Benz ML350 Reliability Rating is 3.0 out of 5. It ranks 27th out of 32 for all car brands.",

    img: "https://i.ibb.co/zh65rsR/car1.jpg",
    rate: "3",
    type: "used",
    year: "2018",
    engine: "Twin Turbo",
    transmission: "7-speed shiftable automatic",
    fuel: "Diesel Direct Injection",
    mileage: "442.8/565.8 mi.",
    color: "blue",
  },
  {
    name: "Mercedes-Benz GL-Class",
    price: "$80,900",
    desc1:
      "The Mercedes-Benz GLS-Class, formerly Mercedes-Benz GL-Class, is a full-size luxury SUV produced by Mercedes-Benz since 2006. According to Mercedes-Benz, it is the SUV equivalent of the Mercedes-Benz S-Class. It is a three-row, seven-passenger vehicle positioned above the GLE-Class (formerly Mercedes-Benz M-Class before 2016), and is the flagship of the Mercedes-Benz SUV line.",
    desc2:
      "The GLS shares the same unibody architecture with the GLE-Class. Most GLS-Class vehicles are assembled at the Mercedes plant in Alabama, except for a small number of early 2007 production vehicles which were manufactured in Germany. The first generation model (X164) was manufactured between 2006 and 2012 and was replaced in 2012 by the new generation GL-Class (X166).",
    desc3: `From 2016 with the release of the facelifted second generation model, the GL-Class was renamed to GLS-Class as per the revised nomenclature adopted by Mercedes. Under this scheme, SUVs use the base name "GL", followed by the model's placement in Mercedes-Benz hierarchy. The "G" is for geländewagen (German for off-road vehicle) and alludes the long-running G-Class. This is followed by the letter "L" that acts as a linkage with the letter "S", the SUV equivalent to the S-Class.`,
    img: "https://i.ibb.co/0XVg3nX/car2.jpg",
    rate: "4",
    type: "used",
    year: "2020",
    engine: "V-Type Diesel Engine",
    transmission: "Automatic",
    fuel: "Diesel Direct Injection",
    mileage: "9.0 kmpl",
    color: "orange",
  },
  {
    name: "Mercedes-Benz GLE-Class",
    price: "$110,500",
    desc1:
      "The 2021 Mercedes-Benz GLE is Mercedes' midsize luxury SUV. Mercedes redesigned it last year, and ever since it's maintained a top spot in our rankings because of its high levels of luxury, refinement and technology. This year, Mercedes is expanding the GLE's lineup with the performance-focused AMG GLE 53 and 63 S variants. These new performance versions only add to the segment's most impressive range of engines, topped by the raucous 603-horsepower AMG GLE 63 S.",
    desc2: `The GLE continues to offer optional third-row seating, exceptional luxury appointments and Mercedes' advanced MBUX infotainment system. It's a great pick for a luxury SUV, though you might also want to check out the Audi Q7, BMW X5 and Volvo XC90 as part of your SUV search. Want more details on the GLE? Check out our Expert Rating for our in-depth test and evaluation.`,
    desc3: `For not a whole lot of extra money than the entry-level four-cylinder GLE, we'd strongly recommend the GLE 450. The 450 upgrades you to a strong and smooth six-cylinder engine that's also respectably fuel-efficient. To that we'd add the Premium package (premium audio system, surround-view camera) and the Driver Assistance Package Plus (an array of extra safety features).`,
    img: "https://i.ibb.co/LgpQX3f/car3.jpg",
    rate: "3",
    type: "used",
    year: "2021",
    engine: "V-Type Diesel Engine",
    transmission: "Automatic",
    fuel: "Diesel Direct Injection",
    mileage: "9.0 kmpl",
    color: "orange",
  },
  {
    name: "Mazda Mazda3",
    price: "$17,000",
    desc1: `The Mazda3 (known as the Mazda Axela in Japan (first three generations), a combination of "accelerate" and "excellent"[4]) is a compact car manufactured in Japan by Mazda. It was introduced in 2003 as a 2004 model, replacing the Familia/323/Protegé in the C-segment. A performance-oriented version of the Mazda3 was marketed as the Mazdaspeed3 in North America, Axela in Japan, and the Mazda 3 MPS in Europe.`,
    desc2: `A second-generation Mazda 3 for the 2009 model year was unveiled in late 2008, with the sedan premiering at the Los Angeles Auto Show and the hatchback at the Bologna Motor Show. For the 2012 model year, Mazda began offering the Mazda 3 with their newly-developed Skyactiv technology, including a more rigid body, a new direct-injection engine, and a new 6-speed transmission.The third generation was introduced in mid-2013 as a 2014 model`,
    desc3: `A fourth-generation Mazda 3 for the 2019 model year was unveiled in November 2018 at the Los Angeles Auto Show and the ASEAN premiere at the Singapore Motor Show. For the 2019 model, the all-new Mazda3 is equipped with the newly-developed Skyactiv technology, including the latest Skyactiv-X, Skyactiv-G and Skyactiv-D engines, each of which provides responsive speed control in any driving situation, and a Spark-Controlled Compression Ignition system.[6][7] The Mazda3 now comes standard with a, previously optional, 2.5-liter engine, and also made all-wheel drive an available option.`,
    img: "https://i.ibb.co/4RGkVQ3/car4.jpg",
    rate: "5",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "red",
  },
  {
    name: "Hyundai Elantra",
    price: "$25,600",
    desc1:
      "The 2021 Hyundai Elantra is a great compact car. It is comfortable and enjoyable to drive, and it has a diverse engine lineup that ranges from highly efficient to high-powered. The front seats are comfy, and the infotainment system is easy to use. Better still, the Elantra provides a ton of standard tech and safety features for a car that starts at under $20,000, and it's backed by a lengthy 10-year/100,000-mile powertrain warranty.",
    desc2: `The Hyundai Elantra is definitely worth a look if you're shopping for a compact sedan. It's affordably priced, packed with features, and enjoyable to drive. That being said, it is up against some fierce competition. You may want to cross-shop the Mazda3, Toyota Corolla, or redesigned Honda Civic before you buy. All three are available in roomier hatchback variants as well, while the Elantra is sedan-only.`,
    desc3: `The Honda Civic and the Elantra are both family-friendly cars that offer class-leading fuel economy, surefooted handling, an easygoing ride, and intuitive tech. Both also come packed with advanced safety features, although you'll get a few more with the Elantra. The Civic stands out as the more premium vehicle, thanks to its suave and finely trimmed interior, but its starting price is also about $1,800 more. The Honda finishes higher in our compact car rankings, but you can't go wrong with either vehicle.`,
    img: "https://i.ibb.co/KNDmSHd/car5.jpg",
    rate: "4",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "silver",
  },
  {
    name: "Kia K900",
    price: "$69,000",
    desc1:
      "The 2020 Kia K900 Luxury starts at $59,900. Standard features include Nappa leather upholstery, a 20-way power-adjustable driver's seat, a 16-way power-adjustable passenger seat, heated and ventilated front seats, heated rear seats, proximity keyless entry, a hands-free trunk, and a sunroof.",
    desc2: `The K9 was launched in South Korea in May 2012, with export sales beginning in late 2012. As of June 2013, it was sold in South Korea, the Middle East, Colombia, Chile, Guatemala, Peru, Russia,[3] the United States, and Canada. There are plans to release it in China, although Kia will not use the Quoris nameplate after it lost a legal battle.[4] The K900 was discontinued in Canada by 2018, and the United States in January 2021.`,
    desc3: `The K9 is a derivative of the Hyundai Equus and Genesis, with which it shares the BH-L (VI) platform. It is the first rear-wheel-drive sedan Kia offered in the United States.[6] The K9's development code was KH.The K9 is slightly shorter than the Equus, and has a longer wheelbase than the Hyundai Genesis with shorter front overhang dimensions. The Quoris features Kia's "Tiger nose" grill as well as blind spot detection, head-up display and an adaptive front lighting system.`,
    img: "https://i.ibb.co/cCfyhvP/car6.jpg",
    rate: "5",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "blue",
  },
  {
    name: "Nissan Pathfinder",
    price: "$35,000",
    desc1:
      "The Nissan Pathfinder is a midsize three-row SUV that we've long praised for its spacious cabin and strong towing figures. Outside of those attributes, however, the previous-generation Pathfinder struggled to make an impact amid a competitive set of rivals that include the Honda Pilot and Kia Telluride. Aiming to boost interest, Nissan has redesigned the Pathfinder for the 2022 model year.",
    desc2: `Compared to the 2020 Pathfinder (there's no 2021 model), the new Pathfinder has more muscular and upright styling, a new nine-speed automatic transmission, retuned steering, additional interior storage and new technology features. We're also pleased that Nissan revised the Pathfinder's suspension tuning for 2022. The previous model's ride quality, in particular, could be overly choppy.`,
    desc3: `Especially in the area of technology, the Pathfinder has grown up quite a bit. It's quieter, more comfortable and better to drive than before. It's worth checking out if you're shopping for a family-friendly three-row SUV, but know that you can get more driving pizzazz from a Honda Pilot or a Kia Telluride or more interior space from a Chevrolet Traverse or a Volkswagen Atlas. Check out our Expert Rating below to get our full analysis of the redesign Pathfinder.`,
    img: "https://i.ibb.co/4S1LHfX/car7.jpg",
    rate: "5",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "Purple",
  },
  {
    name: "Audi Q5",
    price: "$65,000",
    desc1:
      "the 2020 Audi Q5 is a great stable choice as an entry level luxury sports car. It provides everything that you need as it is fast, safe, reliable, and offers good fuel economy. However, if you need a bigger and more powerful engine, then this might not be the one for you.",
    desc2: `The Audi Q5 is a series of compact luxury crossover SUVs produced by the German luxury car manufacturer Audi from 2008.[1] The original first-generation (Typ 8R) model was the third member of the B8 family to be released after the Audi A5 and fourth-generation A4, all being based on the Audi MLB platform. The second generation Q5 (Typ 80A) debuted in 2016 and shares the Audi MLBevo platform with the corresponding B9 versions of the A4 and A5`,
    desc3: `Audi has originally reported that it would offer the Q5 hybrid as launch model,[17] but it was later reported that Audi suspended the plan because of unsatisfactory crash test results for the nickel metal hydride batteries.[18] In 2009, Audi announced it would resume the Q5 hybrid development.[19] It included a 266V, 1.3kWh, battery pack. The Q5 has an all-electric range of about 3 km (2 mi) and maximum all-electric speed of 100 km/h (62 mph).[`,
    img: "https://i.ibb.co/D78X92s/car8.jpg",
    rate: "3",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "Green",
  },
  {
    name: "BMW 550i",
    price: "$60,000",
    desc1:
      "BMW E60 5 Series 550i Specs. With a fuel consumption of 11.1 litres/100km - 25 mpg UK - 21 mpg US (Average), 0 to 100 km/h (62mph) in 5.5 seconds, a maximum top speed of 155 mph (250 km/h), a curb weight of 3605 lbs (1635 kgs), the E60 5 Series 550i has a naturally-aspirated V 8 cylinder engine, Petrol motor.",
    desc2: `The least-expensive 2021 BMW 5 Series is the 2021 BMW 5 Series M550i xDrive 4dr Sedan AWD (4.4L 8cyl Turbo 8A). Including destination charge, it arrives with a Manufacturer's Suggested Retail Price (MSRP) of about $76,800.`,
    desc3: `A 445-horsepower, twin-turbocharged 4.4-liter V8 engine powers the 550i, and the ActiveHybrid 5 is equipped with a turbocharged 3.0-liter six-cylinder engine and an electric motor that together produce 335 horsepower. An eight-speed automatic transmission is standard with all models.`,
    img: "https://i.ibb.co/KXFNZMz/car9.jpg",
    rate: "4",
    type: "used",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "red",
  },
  {
    name: "Acura Elite Specifications",
    price: "$49,500",
    desc1:
      "Acura RDX is a good SUV. It is agile and fun to drive, and its engine delivers plenty of power while returning great fuel economy estimates. Its comfortable interior offers ample space for passengers in both rows, and the cabin is stuffed with high-quality materials.",
    desc2: `the Acura RDX is a good SUV. It is agile and fun to drive, and its engine delivers plenty of power while returning great fuel economy estimates. Its comfortable interior offers ample space for passengers in both rows, and the cabin is stuffed with high-quality materials.`,
    desc3: `Despite being a luxury vehicle, Acura maintenance costs are not as high as Audi maintenance costs, which average about $987 per year, according to RepairPal. Acura ILX maintenance costs around $435 per year, which is on the lower end of the scale for luxury compact cars`,
    img: "https://i.ibb.co/xzGrX1z/car10.jpg",
    rate: "5",
    type: "new",
    year: "2021",
    engine: "v63,01",
    transmission: "Automatic",
    fuel: "Diesel",
    mileage: "85,000",
    color: "Gold",
  },
];
